name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: JoshOpenSource/buildozer-action@v1.3
        with:
          command: buildozer -v android debug
          subfolder: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-android-apk
          path: bin/*.apk
